=== visual-topology/skadi/skadi/jsonschema/package/package_schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "package_schema.json",
  "title": "JSONSchema description of Packages",
  "description": "Specify how Packages are defined in JSON",
  "type": "object",
  "additionalProperties": false,
  "required": ["id","metadata","node_types"],
  "properties": {
    "id": {
      "type": "string",
      "description": "Provide a unique id for this package"
    },
    "executor": {
      "type": "string"
    },
    "configuration": {
      "type": "object",
      "description": "Specify code that handles the package configuration",
      "properties": {
        "classname": {
           "description": "specify the class implementing this packages's configuration, for example (executor=python) this would look like package.subpackage.module.Class"
        }
      }
    },
    "dependencies": {
      "type": "array",
      "description": "Provide a list of the paths/urls of resource dependencies, as understood by the executor",
      "items": {
        "type": "string"
      }
    },
    "metadata": {
      "type": "object",
      "description": "Attach metadata to this package",
      "required": ["name"],
      "additionalProperties": true,
      "properties": {
        "name": {
          "type": "string",
          "description": "Provide a short descriptive name of this package"
        },
        "description": {
          "type": "string",
          "description": "Provide a short description (~1 paragraph) of the purpose of this package"
        },
        "version": {
          "type": "string",
          "description": "Specify the version of the package"
        }
      }
    },
    "display": {
      "type": "object",
      "description": "Specify how nodes in this package are displayed in a network diagram",
      "properties": {
        "icon": {
          "description": "Provide the URL of a SVG icon, relative to the package",
          "type": "string"
        },
        "corners": {
          "description": "Define the shape of the node, in terms of the number of corners",
          "type": "integer"
        },
        "style": {
          "description": "Specify CSS styles to apply to this node's icon",
          "type": "string"
        }
      }
    },
    "l10n": {
      "type": "object",
      "$ref": "file:l10n_schema.json"
    },
    "node_types": {
      "type": "object",
      "description": "mapping from a node type id to its definition",
      "patternProperties": {
        ".*": {
          "type": "object",
          "$ref": "file:node_type_schema.json"
        }
      }
    },
    "link_types": {
      "type": "object",
      "description": "mapping from a link type id to its definition",
      "patternProperties": {
        ".*": {
          "type": "object",
          "$ref": "file:link_type_schema.json"
        }
      }
    }
  }
}

=== visual-topology/skadi/docs/api/example-packages/dataviz/schema.json
{
    "id": "dataviz",
    "metadata": {
        "name": "Data Viz Example Package",
        "version": "0.0.1",
        "description": "A simple example package for building data visualizations",
        "link": "about.html"
    },
    "display": {
        "style": "fill:lightgrey;"
    },
    "executor": "javascript",
    "configuration": {
        "classname": "DataVizExample.Configuration",
        "pages": {
            "default": {
                "button_label": "Configure...",
                "title": "DataViz Configuration",
                "url": "configuration.html"
            }
        }
    },
    "dependencies": [ "https://cdn.jsdelivr.net/npm/arquero@latest", "configuration.js","nodes/aq_utils.js", "nodes/chart.js" ],
    "node_types": {
        "csv_import": {
            "metadata": {
                "name": "CSV Reader",
                "description": "Select a CSV file and load it into a dataset"
            },
            "output_ports": {
                "data_out": {
                    "link_type": "dataviz:dataset"
                }
            },
            "display": {
                "corners": 7,
                "icon": "icons/csv_import.svg"
            },
            "pages": {
                "default": {
                    "menu_label":"Open...",
                    "menu_tab_label":"Open in new tab...",
                    "title": "CSV Import",
                    "url": "nodes/csv_import.html",
                    "window_width": 500,
                    "window_height": 300
                }
            },
            "classname": "DataVizExample.CsvImportNode",
            "dependencies": ["nodes/csv_import.js"]
        },
        "data_retyper": {
            "metadata": {
                "name": "Data Retyper",
                "description": "Inspect and change the column types"
            },
            "input_ports": {
                "data_in": {
                    "link_type": "dataviz:dataset"
                }
            },
            "output_ports": {
                "data_out": {
                    "link_type": "dataviz:dataset"
                }
            },
            "display": {
                "corners": 7,
                "icon": "icons/data_retyper.svg"
            },
            "pages": {
                "default": {
                    "menu_label":"Open...",
                    "menu_tab_label":"Open in new tab...",
                    "title": "Retype Columns",
                    "url": "nodes/data_retyper.html",
                    "window_width": 800,
                    "window_height": 600
                }
            },
            "classname": "DataVizExample.DataRetyperNode",
            "dependencies": ["nodes/data_retyper.js"]
        },
        "sample_rows": {
            "metadata": {
                "name": "Sample",
                "description": "Select a sample from the input dataset"
            },
            "input_ports": {
                "data_in": {
                    "allow_multiple_connections": false,
                    "link_type": "dataviz:dataset"
                }
            },
            "output_ports": {
                "data_out": {
                    "link_type": "dataviz:dataset"
                }
            },
            "display": {
                "corners": 7,
                "icon": "icons/filter_random.svg"
            },
            "pages": {
                "default": {
                    "menu_label": "Open...",
                    "menu_tab_label":"Open in new tab...",
                    "title": "Sample Rows",
                    "url": "nodes/sample_rows.html",
                    "window_width": 500,
                    "window_height": 300
                }
            },
            "classname": "DataVizExample.SampleRowsNode",
            "dependencies": ["nodes/sample_rows.js"]
        },
        "select_rows": {
            "metadata": {
                "name": "Select Rows",
                "description": "Select Rows by Category or Numeric Range"
            },
            "input_ports": {
                "data_in": {
                    "allow_multiple_connections": false,
                    "link_type": "dataviz:dataset"
                }
            },
            "output_ports": {
                "data_out": {
                    "link_type": "dataviz:dataset"
                }
            },
            "display": {
                "corners": 7,
                "icon": "icons/select_rows.svg"
            },
            "pages": {
                "default": {
                    "menu_label": "Open...",
                    "menu_tab_label":"Open in new tab...",
                    "title": "Select Rows",
                    "url": "nodes/select_rows.html",
                    "window_width": 600,
                    "window_height": 600
                }
            },
            "classname": "DataVizExample.SelectRowsNode",
            "dependencies": ["nodes/select_rows.js"]
        },
        "join_rows": {
            "metadata": {
                "name": "Join Rows",
                "description": "Join rows from multiple inputs"
            },
            "input_ports": {
                "data_in1": {
                    "allow_multiple_connections": false,
                    "link_type": "dataviz:dataset"
                },
                "data_in2": {
                    "allow_multiple_connections": false,
                    "link_type": "dataviz:dataset"
                }
            },
            "output_ports": {
                "data_out": {
                    "link_type": "dataviz:dataset"
                }
            },
            "display": {
                "corners": 7,
                "icon": "icons/join_rows.svg"
            },
             "pages": {
                "default": {
                    "menu_label": "Open...",
                    "menu_tab_label":"Open in new tab...",
                    "title": "Join Rows",
                    "url": "nodes/join_rows.html",
                    "window_width": 600,
                    "window_height": 600
                }
            },
            "classname": "DataVizExample.JoinRowsNode",
            "dependencies": ["nodes/join_rows.js"]
        },
         "select_columns": {
            "metadata": {
                "name": "Select Columns",
                "description": "Select a subset of columns"
            },
            "input_ports": {
                "data_in": {
                    "allow_multiple_connections": false,
                    "link_type": "dataviz:dataset"
                }
            },
            "output_ports": {
                "data_out": {
                    "link_type": "dataviz:dataset"
                }
            },
            "display": {
                "corners": 7,
                "icon": "icons/select_columns.svg"
            },
            "pages": {
                "default": {
                    "menu_label": "Open...",
                    "menu_tab_label":"Open in new tab...",
                    "title": "Select Columns",
                    "url": "nodes/select_columns.html",
                    "window_width": 600,
                    "window_height": 600
                }
            },
            "classname": "DataVizExample.SelectColumnsNode",
            "dependencies": ["nodes/select_columns.js"]
        },
        "create_column": {
            "metadata": {
                "name": "Create Column",
                "description": "Create a new column"
            },
            "input_ports": {
                "data_in": {
                    "allow_multiple_connections": false,
                    "link_type": "dataviz:dataset"
                }
            },
            "output_ports": {
                "data_out": {
                    "link_type": "dataviz:dataset"
                }
            },
            "display": {
                "corners": 7,
                "icon": "icons/create_column.svg"
            },
            "pages": {
                "default": {
                    "menu_label": "Open...",
                    "menu_tab_label":"Open in new tab...",
                    "title": "Create Column",
                    "url": "nodes/create_column.html"
                }
            },
            "classname": "DataVizExample.CreateColumnNode",
            "dependencies": ["nodes/create_column.js"]
        },
        "table_display": {
            "metadata": {
                "name": "Table Display",
                "description": "Display a dataset in a table"
            },
            "input_ports": {
                "data_in": {
                    "allow_multiple_connections": false,
                    "link_type": "dataviz:dataset"
                }
            },
            "display": {
                "corners": 7,
                "icon": "icons/table.svg"
            },
            "pages": {
                "default": {
                    "menu_label": "Open...",
                    "menu_tab_label":"Open in new tab...",
                    "title": "Table",
                    "url": "nodes/table_display.html",
                    "window_width": 800,
                    "window_height": 600
                }
            },
            "classname": "DataVizExample.TableDisplayNode",
            "dependencies": ["nodes/table_display.js"]
        },
        "scatter_plot": {
            "metadata": {
                "name": "Scatter Plot",
                "description": "Plot points for each data item"
            },
            "input_ports": {
                "data_in": {
                    "allow_multiple_connections": false,
                    "link_type": "dataviz:dataset"
                }
            },
            "display": {
                "corners": 5,
                "icon": "icons/scatter.svg"
            },
            "pages": {
                "default": {
